# Generated by Django 4.0.6 on 2024-10-16 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='tos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tos.tos', verbose_name='Тос'),
        ),
    ]
